name: Sync OneDrive to Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone for OneDrive
        run: |
          rclone config create onedrive onedrive token '{"access_token":"<your token>"}'

      - name: Sync files from OneDrive to repo
        run: |
          rclone copy onedrive:/PowerAutomateUploads ./ --update
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto upload from Power Automate" || echo "No changes"
          git push
