name: Sync OneDrive PDFs to Repo

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:        # allows manual run

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone from Base64 secret
        run: |
          mkdir -p ~/.config/rclone
          echo "${RCLONE_CONF_BASE64}" | base64 -d > ~/.config/rclone/rclone.conf
        env:
          RCLONE_CONF_BASE64: ${{ secrets.RCLONE_CONF_BASE64 }}

      - name: Sync OneDrive folder to repo
        run: |
          rclone copy onedrive:/PowerAutomateUploads ./ --update
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Auto upload from Power Automate" || echo "No changes to commit"
          git push
