name: Sync OneDrive PDFs to Repo

on:
  workflow_dispatch:           # Manual trigger
  repository_dispatch:         # Triggered from Power Automate
    types: [sync]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # Get full history for proper pull/rebase

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone from Base64 secret
        run: |
          mkdir -p ~/.config/rclone
          echo "${RCLONE_CONF_BASE64}" | base64 -d > ~/.config/rclone/rclone.conf
        env:
          RCLONE_CONF_BASE64: ${{ secrets.RCLONE_CONF_BASE64 }}

      - name: Sync OneDrive folder to repo
        run: |
          # Sync files from OneDrive
          rclone copy onedrive:/GithubUploads ./ --update

          # Configure Git
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Add only new/changed files
          git add -A

          # Commit only if changes exist
          git commit -m "Auto upload from Power Automate" || echo "No changes to commit"

          # Pull latest remote commits to avoid push rejection
          git pull --rebase origin main

          # Push changes
          git push origin main
